config/routes.rb
Trackie::Application.routes.draw do
  devise_for :users, controllers:{ registrations: "registrations",
    :omniauth_callbacks => "users/omniauth_callbacks",
    :invitations => 'users/invitations'
  }

  root 'welcome#index'

  resources :income_types
  resources :incomes
  
  resources :expense_types
  resources :expenses
  
  post "versions/:id/revert" => "versions#revert", :as => "revert_version"

end

app/controllers/income_types_controller.rb
class IncomeTypesController < ApplicationController

  helper_method :income_type
  

  def index
    @income_types = current_user.income_types.page(params[:page]).per(15).includes(:parent)
  end
  
  def new
    @income_type = current_user.income_types.new
  end

  def create
    @income_type = current_user.income_types.build(resource_params)
    if income_type.save
      redirect_to income_types_path, notice: "Income Type #{income_type.name} was saved!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if income_type.update(resource_params)
      redirect_to income_types_path, notice: "Income Type #{income_type.name} was saved!"
    else
      render :edit
    end
  end

  def destroy    
      income_type.destroy
      redirect_to income_types_path , :notice => "Income Type #{income_type.name} deleted!"
  end

  def income_type
    @income_type ||= current_user.income_types.find(params[:id])
  end

  private
    def resource_params
      params.require(:income_type).permit(:name, :parent_id)
    end
end

app/helpers/income_type_helper.rb
module IncomeTypeHelper
  def delete_button income_type
    if income_type.children.any? or income_type.incomes.any?
      link_to 'Delete', '#',
      :disabled => true,
      :class => 'btn btn-mini btn-danger',
      title: 'You must delete all children and all incomes of this type.', rel: 'tooltip'
    else
      link_to 'Delete',
      income_type_path(income_type),
      :method => :delete,
      :data => { :confirm => "Press Ok to Delete the Income Type #{income_type.name} ?"},
      :class => 'btn btn-mini btn-danger'
    end
  end

  def select_income_types
    if income_type.children.any?
      return current_user.income_types.none
    end
    current_user.income_types.where('parent_id is ? AND id is not ? ', nil, income_type.id)
  end
  
end

app/views/income_types/_form.html.erb
<div class="border-form-div">
  <%= simple_form_for income_type do |f| %>
    <%= f.error_notification %>
    <div class="control-group">
      <%= f.input :name%>
      <%= f.input :parent_id, :collection => select_income_types, :value_method => :id,
        :label_method =>:name, :include_blank => "None", :label => "Parent" %>
    </div>
    <div class="form-actions">
      <%= f.button :submit %> or 
      <%= link_to "Cancel", income_types_path %>
    </div>
  <%end%>
</div>

app/views/income_types/edit.html.erb
<div class="page-header">
  <h1 class="text-center">Edit Income Type</h1>
</div>

<%= render :partial => 'form' %>

app/views/income_types/index.html.erb
<div class="page-header">
  <h1 class="text-center">Income Types</h1>
</div>
<div class="new-button">
  <%= link_to 'New Income Type',
            new_income_type_path,
            :class => 'btn btn-primary' %>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Parent</th>
      <th>Options</th>
    </tr>
  </thead>
  <tbody>
    <% @income_types.each do |income_type| %>
      <tr>
        <td><%= income_type.name %></td>
        <td><%= income_type.parent ? income_type.parent.name :  'None' %></td>
        <td>
          <%= link_to 'Edit', edit_income_type_path(income_type), :class => 'btn btn-mini' %>
          <%= delete_button( income_type)%>
        </td>
      </tr>
    <% end %>
    <tr >
      <td colspan='4'>
       <%= paginate @income_types %>
      </td>
    </tr>
  </tbody>
</table>

app/views/income_types/new.html.erb
<div class="page-header">
  <h1 class="text-center">New Income Type</h1>
</div>

<%= render :partial => 'form' %>