config/routes.rb
Trackie::Application.routes.draw do
  devise_for :users, controllers:{ registrations: "registrations",
    :omniauth_callbacks => "users/omniauth_callbacks",
    :invitations => 'users/invitations'
  }

  root 'welcome#index'

  resources :income_types
  resources :incomes
  
  resources :expense_types
  resources :expenses
  
  post "versions/:id/revert" => "versions#revert", :as => "revert_version"

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @last_income = current_user.incomes.last
    @last_expense = current_user.expenses.last
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="page-header">
  <h1 class="text-center">Welcome to Trackie,  <span style="color: blue;"><%= current_user.name %></span></h1>
</div>
<div id='welcome'>
  <h4>What do you want to do today? </h4>
  
  <h4>
    <% if @last_income %>
      Your last added income is: 
      <span class="income" ><%= @last_income.amount %></span>
      in <%= "#{@last_income.income_type.parent.name} /" if @last_income.income_type.parent %>
      <%= @last_income.income_type.name %>
    <% else %>
      You don't have any Incomes.
    <% end %>
      - <%= link_to 'add new', new_income_path %> Income
  </h4>

  <h4>
    <% if @last_expense %>
      Your last added expense is:
      <span class="expense"><%=  @last_expense.amount %></span>
      in <%= "#{@last_expense.expense_type.parent.name} /" if @last_expense.expense_type.parent %>
      <%= @last_expense.expense_type.name  %>
    <%else %>
      You don't have any Expenses
    <%end%>
    - <%= link_to 'add new', new_expense_path %> Expense
  </h4>

  <h4>
    You balance for this month is:
     <span class="<%= balance >0 ? 'income' : 'expense' %>"><%= @balance %></span>.
  </h4>
</div>