config/routes.rb
Trackie::Application.routes.draw do
  devise_for :users, controllers:{ registrations: "registrations",
    :omniauth_callbacks => "users/omniauth_callbacks",
    :invitations => 'users/invitations'
  }

  root 'welcome#index'

  resources :income_types
  resources :incomes
  
  resources :expense_types
  resources :expenses
  
  post "versions/:id/revert" => "versions#revert", :as => "revert_version"

end

app/models/income.rb
class Income < ActiveRecord::Base
  validates :income_type, :income_type_id, :amount, presence:  true
  validates_numericality_of :amount, :greater_than_or_equal_to => 0
  belongs_to :income_type
  belongs_to :user
  has_paper_trail
end

app/models/income_type.rb
class IncomeType < ActiveRecord::Base
  validates :name, presence:  true, length: { maximum: 50 }
  validates_uniqueness_of :name, scope: :user_id
  
  belongs_to :parent, class_name: "IncomeType"
  belongs_to :user
  has_many :children, class_name: "IncomeType", foreign_key: "parent_id"
  has_many :incomes

  def children_with_parent
    [self].concat self.children
  end

end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController

  helper_method :income

  def index
    @incomes = current_user.incomes.where(:created_at =>  Time.current.all_month).includes(:income_type).page(params[:page]).per(10).reverse_order
  end
  
  def new
    @income = current_user.incomes.new
  end

  def create
    @income = current_user.incomes.build(resource_params)
    if @income.save
      redirect_to new_income_path, notice: "You added #{income.amount} to your Income this month."
    else
      render :new
    end
  end

  def destroy
    income.destroy
    redirect_to incomes_path, notice: "Income #{income.amount} from #{income.income_type.name} is deleted." +
    " Press #{undo_link} to add it back"
  end

  def income
    @income ||= current_user.incomes.find(params[:id])
  end

  private
    def resource_params
      params.require(:income).permit(:income_type_id, :amount, :note)
    end

    def undo_link
      view_context.link_to("undo", revert_version_path(income.versions.scoped.last), :method => :post)
    end
end

app/helpers/incomes_helper.rb
module IncomesHelper
  def income_type_collection
    current_user.income_types.where('parent_id is ?', nil).includes(:children)
  end
end

app/views/incomes/_form.html.erb
<div class="border-form-div">
  <%= simple_form_for income, :html => { :class => 'form-horizontal' } do |f| %>
    <%= f.error_notification %>
    <div class="control-group">
      <%= f.input :income_type_id, collection: income_type_collection, as: :grouped_select,
        group_method: :children_with_parent,:value_method => :id, :label_method =>:name,
        prompt: "Choose income type"%>
      <%= f.input :amount %>
      <%= f.input :note %>
    </div>
    <div class="form-actions">
      <%= f.button :submit %> or 
      <%= link_to "Cancel", incomes_path %>
    </div>
  <%end%>
</div>

app/views/incomes/index.html.erb
<div class="page-header">
  <h1 class="text-center">Incomes</h1>
</div>
<div class="new-button">
  Add <%= link_to 'New', new_income_path, :class => 'btn btn-primary' %> Income
</div>
<div style="margin-left: 20px;">
  <h3>Total from beginning of the month: <%= monthly_income %>  RON</h3>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Income Type</th>
      <th>Amount</th>
      <th>Note</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @incomes.each do |income| %>
      <tr>
        <td><%= link_to income.id, income_path(income) %></td>
        <td><%= income.income_type.name %></td>
        <td><%= income.amount %></td>
        <td><%= income.note %></td>
        <td><%= income.created_at %></td>
        <td>
          <%= link_to 'Delete',
                      income_path(income),
                      :method => :delete,
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
     <tr>
        <td colspan="4">
          <%= paginate @incomes %>
        </td>
      </tr>
  </tbody>
</table>

app/views/incomes/new.html.erb
<div class="page-header">
  <h1 class="text-center">Add New Income</h1>
</div>

<%= render :partial => 'form' %>