config/routes.rb
Trackie::Application.routes.draw do
  devise_for :users, controllers:{ registrations: "registrations",
    :omniauth_callbacks => "users/omniauth_callbacks",
    :invitations => 'users/invitations'
  }

  root 'welcome#index'

  resources :income_types
  resources :incomes
  
  resources :expense_types
  resources :expenses
  
  post "versions/:id/revert" => "versions#revert", :as => "revert_version"

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  helper_method :expense

  def index
    @expenses = current_user.expenses.where(:created_at =>  Time.current.all_month).includes(:expense_type).page(params[:page]).per(10).reverse_order
  end
  
  def new
    @expense = current_user.expenses.new
  end

  def create
    @expense = current_user.expenses.build(resource_params)
    if @expense.save
      redirect_to new_expense_path, notice: "You added #{expense.amount} to your expense this month."
    else
      render :new
    end
  end

  def destroy
    expense.destroy
    redirect_to expenses_path, notice: "expense #{expense.amount} from #{expense.expense_type.name} is deleted." +
    " Press #{undo_link} to add it back"
  end

  def expense
    @expense ||= current_user.expenses.find(params[:id])
  end

  private
    def resource_params
      params.require(:expense).permit(:expense_type_id, :amount, :note)
    end

    def undo_link
      view_context.link_to("undo", revert_version_path(expense.versions.scoped.last), :method => :post)
    end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
  def expense_type_collection
    current_user.expense_types.where('parent_id is ?', nil).includes(:children)
  end
end

app/views/expenses/_form.html.erb
<div class="border-form-div">
  <%= simple_form_for expense do |f| %>
   <%= f.error_notification %>
   <div class="control-group">
     <%= f.input :expense_type_id, collection: expense_type_collection, as: :grouped_select,
      group_method: :children_with_parent, :value_method => :id, :label_method =>:name,
      prompt: "Choose expense type"%>
     <%= f.input :amount %>
     <%= f.input :note %>
   </div>
   <div class="form-actions">
     <%= f.button :submit %> or 
     <%= link_to "Cancel", expenses_path %>
   </div>
  <%end%>
</div>

app/views/expenses/index.html.erb
<div class="page-header">
  <h1 class="text-center">Expenses</h1>
</div>

<div class="new-button">
  Add <%= link_to 'New', new_expense_path, :class => 'btn btn-primary' %> Expense
</div>
<div style="margin-left: 20px;">
  <h3>Total from beginning of the month: <%= monthly_expense %>  RON</h3>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Expense Type</th>
      <th>Amount</th>
      <th>Note</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @expenses.each do |expense| %>
      <tr>
        <td><%= link_to expense.id, expense_path(expense) %></td>
        <td><%= expense.expense_type.name %></td>
        <td><%= expense.amount %></td>
        <td><%= expense.note %></td>
        <td><%= expense.created_at %></td>
        <td>
          <%= link_to 'Delete',
                      expense_path(expense),
                      :method => :delete,
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
     <tr>
        <td colspan="4">
          <%= paginate @expenses %>
        </td>
      </tr>
  </tbody>
</table>

app/views/expenses/new.html.erb
<div class="page-header">
  <h1 class="text-center">Add New Expense</h1>
</div>

<%= render :partial => 'form' %>